[package]
name = "wasm-pqc-subtle"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ml-dsa = "0.0.4"
ml-kem = "0.2.2"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
rand_core = { version = "0.6", features = ["getrandom"] }
